language: node_js
node_js:
  - "lts/*"
git:
  submodules: false
cache:
  directories:
    "node_modules"
before_script:
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
